version: '3'
services:
  ansible1:
     build:
        context: .
        dockerfile: Dockerfile
     image: ansible-master
     privileged: yes
     container_name: ansible-master
     #links:
     #   - ansible2
     dns:
       - 8.8.8.8
       - 8.8.4.4
     networks:
        test1:
          ipv4_address: 192.168.0.2
     dns_search:
         - siva.local
     cap_add:
         - ALL
     tty: yes
     volumes:
       - ./hosts:/etc/ansible/hosts
  ansible2:
      depends_on: 
        - ansible1
      build:
        context: .
        dockerfile: Dockerfile-slave
      image: ansible-slave
      privileged: yes
      container_name: ansible-slave1
      links:
              - ansible1:ansible1
      dns:
        - 8.8.8.8
        - 8.8.4.4
      networks:
        test1:
          ipv4_address: 192.168.0.3
      dns_search:
         - siva.local
      cap_add:
         - ALL
      tty: yes
  ansible3:
      depends_on: 
        - ansible1
        - ansible2
      build:
        context: .
        dockerfile: Dockerfile-slave
      image: ansible-slave
      privileged: yes
      container_name: ansible-slave2
      links:
              - ansible1:ansible1
              - ansible2:ansible2
      dns:
        - 8.8.8.8
        - 8.8.4.4
      networks:
        test1:
          ipv4_address: 192.168.0.4
      dns_search:
         - siva.local
      cap_add:
         - ALL
      tty: yes
networks:
  test1:
     driver: bridge
     ipam:
       driver: default
       config:
         - subnet: 192.168.0.0/16
           #gateway: "192.168.0.1"
