image: node:10.16.3
name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10.16.3]

    steps:
    - uses: actions/checkout@v2
    #- name: Setup node
     # uses: actions/setup-node@v2.5.1
     # with:
       # node-version: ${{ matrix.node }}
    - run: node -v
    #- run: |
        ##cd build
        #npm install
        #npm install colors -g
        #npm install -g sfcc-ci --save-dev
