name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    #strategy:
      #matrix:
        #node: [10.16.3]

    steps:
    - uses: actions/setup-node@v10.16.3
    - uses: actions/checkout@v2
    - name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      run: node -v
